Adding docker support for the ML Learning
danasekarane-ta/mle-training pull request #28
Opened 2024-05-31 07:15 UTC by danasekarane-ta

For this exercise I have completed these steps

a. Build a docker container for your application and test it runs as expected locally
by running the container and using the same steps as in the previous module to
test your web application (MLFlow UI). Once you have a working container,
branch off of v0.3 Git tag and create a PR in your repository and submit the PR
link.
b. Create a DockerHub account for yourself (free a/c).
c. Prepare a Dockerfile for the Web Application.
d. Build the Docker image and push your image to your DockerHub Registry with a
custom tag.
e. Try pulling the image from DockerHub and running the instance and testing
everything works as expected. Once tested, submit the DockerHub link.

3. Setup a github workflow job for building the container and pushing to DockerHub:
a. Checkout to the repository in the workflow
b. Login to your DockerHub (ref. GH actions docker loging) with your DockerHub
credentials saved as GitHub Secrets (ref. Using GH Secrets in GH Actions)
c. Build the container-image from the Dockerfile and push the image to your
DockerHub registry.
d. Assign an appropriate tag to the image before pushing to the Registry.

DOCKER HUB LINKS:
1. FROM LOCAL PUSH: https://hub.docker.com/layers/danasekaraneta/mlflowlearning/latest/images/sha256-76cdbf89f9cf9e684c8904c977896f49eb7875463c1c9d3cd68391ac1c2797fc?context=repo
2. FROM GITHUBACTIONS: https://hub.docker.com/layers/danasekaraneta/mlflowlearning/github-latest/images/sha256-4957bd83a72b83c1245ab9af7b882bf8c8ba53dc7428b0cbe8061eb347150793?context=repo

2024-05-31 07:48 UTC, abilashravi-ta requested changes

2024-05-31 07:48 UTC, abilashravi-ta commented on requirements.txt
> +mlflow
why do we need this `requirements.txt`?
does `env.yml` not have all these.??

2024-05-31 07:48 UTC, abilashravi-ta commented on Dockerfile
> +CMD [ "/bin/sh", "-c", "mlflow server --backend-store-uri mlruns/ --default-artifact-root mlruns/ --host 0.0.0.0 --port 5008 \
Can you move this _Dockerfile_ to `deploy/docker/`..
Also your `env.yml` must be inside `deploy/conda/`.
Refer [Project layout](https://docs.google.com/document/d/1FR--XjjbFCoMzxYAKFe5FJtTnjDpgRH9FFqMagEYl3g/edit)

2024-05-31 09:48 UTC, danasekarane-ta commented
@abilashravi-ta Changes Pushed

2024-06-04 05:13 UTC, abilashravi-ta approved these changes

2024-06-04 05:34 UTC, merged